import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

const poppins = Poppins({
  weight: ["100", "200", "400", "500", "600", "800"]
})

export const metadata = {
  title: {
    default: "Hero Kidz",
    template: "%s | Hero kidz"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
    >
      <body className={`${poppins.className} antialiased`}>
        <header className="py-2 md:w-11/12 mx-auto">
          <Navbar></Navbar>
        </header>

        <main className="py-2 md:w-11/12 mx-auto min-h-screen">
          {children}
        </main>

        <footer className="py-2 md:w-11/12 mx-auto">
          <Footer></Footer>
        </footer>
        </body>
    </html>
  );
}
