import React from 'react';

export const metadata = {
  title: "All Products",
  description: "Generated by create next app",
};

const ProductPage = () => {
    return (
        <div>
            productPage
        </div>
    );
};

export default ProductPage;