import { getProducts } from '@/actions/server/product';
import ProductCard from '@/components/cards/ProductCard';
import React from 'react';

export const metadata = {
  title: "All Products",
  description: "Generated by create next app",
};

const ProductPage = async() => {
    const products = await getProducts() || [];
    return (
        <div>
            <h2 className='text-center text-4xl font-bold py-4 rounded mt-5'>Our Products</h2>
            <div className='grid grid-cols-3 gap-4'>
                {
                    products.map((product)=> (<ProductCard key={product.name} product={product}></ProductCard>))
                }
            </div>
        </div>
    );
};

export default ProductPage;